services:
  frontend:
    image: projetual
    build: .
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - 5173:5173
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "250"
    volumes:
      - ./:/app
