/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f9f9ff',
        'surface-container-high': '#dee8ff',
        'on-primary-fixed': '#001b3c',
        'primary-fixed-dim': '#adc7f7',
        'surface-dim': '#cfdaf1',
        'on-secondary-fixed-variant': '#00497e',
        'on-error': '#ffffff',
        outline: '#74777f',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#5f4100',
        'secondary-fixed': '#d2e4ff',
        'secondary-container': '#66affe',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#9fcaff',
        tertiary: '#2d1d00',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'on-primary-container': '#86a0cd',
        'on-tertiary-container': '#cb9524',
        'inverse-surface': '#263142',
        'on-surface': '#111c2c',
        'surface-bright': '#f9f9ff',
        primary: '#002045',
        'on-secondary-container': '#004172',
        'surface-variant': '#d8e3fa',
        'on-secondary-fixed': '#001d37',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#f8bc4b',
        'inverse-on-surface': '#ebf1ff',
        'primary-fixed': '#d6e3ff',
        'surface-tint': '#455f88',
        'outline-variant': '#c4c6cf',
        surface: '#f9f9ff',
        'on-tertiary-fixed': '#271900',
        'on-surface-variant': '#43474e',
        'on-background': '#111c2c',
        'inverse-primary': '#adc7f7',
        'surface-container': '#e7eeff',
        secondary: '#0061a5',
        'primary-container': '#1a365d',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#ffdeaa',
        'surface-container-low': '#f0f3ff',
        'surface-container-highest': '#d8e3fa',
        'tertiary-container': '#493100',
        'on-primary-fixed-variant': '#2d476f',
      },
      fontFamily: {
        headline: ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
